Feature/research client
Groupe-5-JEE/Hire pull request #9
Opened 2020-11-19 19:04 UTC by wilfried7

2020-11-19 20:45 UTC, zartech22 requested changes, later dismissed
Manque la javadoc. Petite question également : doit-on garder les interface CutomerManager, TechnicalManager, ... ? SI on fait des DAO qui font leur boulot ?

2020-11-19 20:45 UTC, zartech22 commented on src/controller/SearchCustomerController.java
> -		super.doGet(req, resp);
À remettre pour empêcher quelqu'un de non connecté d'accéder à la page

2020-11-19 20:45 UTC, zartech22 commented on src/controller/SearchCustomerController.java
> +		System.out.println(customers);
On retire les messages de debug ?

2020-11-19 20:45 UTC, zartech22 commented on src/controller/SearchCustomerController.java
> +
Serait-il intéressant de mettre ceci dans une méthode du base controller afin de centraliser cette partie qui se répettera dans plusieurs controller ?

2020-11-19 20:45 UTC, zartech22 commented on src/dao/CustomerDao.java
>  	EntityManager em = DBManager.getEntityManager();
private

2020-11-20 07:17 UTC, DoBrcd requested changes

2020-11-20 07:17 UTC, DoBrcd commented on src/controller/SearchCustomerController.java
> +		ArrayList<Customer> customers = customerService.getAllCustomers();
Change pour une List : permet plus de liberté sur l'implémentation de la fonction customerService.getAllCustomers()

2020-11-20 07:17 UTC, DoBrcd commented on src/controller/SearchCustomerController.java
> +
J'ai créer une issue #11  pour moi pas besoin de le regler ici

2020-11-20 07:17 UTC, DoBrcd commented on src/dao/CustomerDao.java
> +	public ArrayList<Customer> getAllCustomers(){
Je préfèrerais que ce soit une List
attention doublons dans les fonction (getAll et getAllCustomers)

2020-11-20 07:17 UTC, DoBrcd commented on src/dao/CustomerDaoInterface.java
> +	public ArrayList<Customer> getAllCustomers();
List

2020-11-20 07:17 UTC, DoBrcd commented on src/model/GeneralManager.java
Remove ?

2020-11-20 07:17 UTC, DoBrcd commented on src/service/CustomerServiceImp.java
> +	public ArrayList<Customer> getAllCustomers() {
List

2020-11-20 07:17 UTC, DoBrcd commented on src/service/CustomerServiceInterface.java
> +	public ArrayList<Customer> getAllCustomers();
List

2020-11-20 07:17 UTC, DoBrcd commented on src/service/CustomerServiceInterface.java
>  	public List<Customer>  getAll();
Attention doublons

2020-11-20 08:00 UTC, DoBrcd commented
Pour répondre à ta question Kévin je pense que si à la fin on utilise toujours pas les interfaces on les virera

2020-11-20 10:21 UTC, DoBrcd commented on src/controller/SearchCustomerController.java
> +		System.out.println(customers);
Je suis pour

2020-11-20 13:49 UTC, DoBrcd requested changes
Not a lot to change but I want it perfect

2020-11-20 13:49 UTC, DoBrcd commented on WebContent/client/research.jsp
> +		java.util.List<model.Customer> customers = (java.util.List<model.Customer>) request.getAttribute("customers");
Maybe use an import at the begin of the file ?

2020-11-20 13:49 UTC, DoBrcd commented on src/dao/CustomerDaoInterface.java
> +	 * @param
I think you can remove the @param line

2020-11-20 13:49 UTC, DoBrcd commented on src/model/GeneralManager.java
> +
Unused import ?

2020-11-20 14:40 UTC, DoBrcd approved these changes
Good Job

2020-11-20 15:03 UTC, merged